# Generated by Django 5.1 on 2024-08-27 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=30)),
                ('officer_contact', models.CharField(max_length=30)),
                ('officer_email', models.EmailField(max_length=30)),
                ('officer_address', models.CharField(max_length=30)),
                ('officer_dob', models.DateField()),
                ('officer_photo', models.FileField(upload_to='Assets/Officer/Photo/')),
                ('officer_proof', models.FileField(upload_to='Assets/Officer/Proof/')),
                ('officer_gender', models.CharField(max_length=5)),
                ('officer_status', models.IntegerField(default=0)),
                ('officer_password', models.CharField(max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_designation')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_admin')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_officer')),
            ],
        ),
    ]
