# Generated by Django 5.1 on 2024-08-27 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_place'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=1000)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='Assets/ChatFiles/')),
                ('admin_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_from', to='Admin.tbl_admin')),
                ('admin_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_to', to='Admin.tbl_admin')),
                ('officer_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer_from', to='Guest.tbl_officer')),
                ('officer_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officer_to', to='Guest.tbl_officer')),
            ],
        ),
    ]
