# Generated by Django 5.1 on 2024-08-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_chat',
            name='chat_content',
            field=models.TextField(),
        ),
    ]
