# Generated by Django 5.1 on 2024-08-27 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_worktype'),
        ('Guest', '0004_alter_tbl_chat_chat_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_description', models.CharField(max_length=100)),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('assign_status', models.IntegerField(default=0)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_officer')),
                ('worktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_worktype')),
            ],
        ),
    ]
