# Generated by Django 5.1 on 2024-08-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_assign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assign',
        ),
    ]
